resources:
- name: repo
  type: git
  uri: git@github.com:scalasm/concourse-sandbox.git
  branch: main

jobs:
- name: hello-world-job
  plan:
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]
